"""add_connection_requests

Revision ID: 00b16a0c0c78
Revises: 6d4e3f2a1b0c
Create Date: 2026-08-18 20:41:18.538273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b16a0c0c78'
down_revision: Union[str, Sequence[str], None] = '6d4e3f2a1b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connection_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('receiver_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connection_requests_receiver_id'), 'connection_requests', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_connection_requests_sender_id'), 'connection_requests', ['sender_id'], unique=False)
    op.create_index(op.f('ix_connection_requests_status'), 'connection_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connection_requests_status'), table_name='connection_requests')
    op.drop_index(op.f('ix_connection_requests_sender_id'), table_name='connection_requests')
    op.drop_index(op.f('ix_connection_requests_receiver_id'), table_name='connection_requests')
    op.drop_table('connection_requests')
    # ### end Alembic commands ###
