"""Add insights to contact_memories

Revision ID: 40169e3d7c2b
Revises: 6bcc6defa0aa
Create Date: 2026-08-10 12:07:04.193391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40169e3d7c2b'
down_revision: Union[str, Sequence[str], None] = '6bcc6defa0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_memories', sa.Column('insights', sa.JSON(), nullable=True))
    op.add_column('search_history', sa.Column('results', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'results')
    op.drop_column('contact_memories', 'insights')
    # ### end Alembic commands ###
