"""add_tags_ai_config

Revision ID: 4440d31ed760
Revises: 5756ce2b4a1c
Create Date: 2026-08-21 10:18:56.545567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4440d31ed760'
down_revision: Union[str, Sequence[str], None] = '5756ce2b4a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_system_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_system_config_key'), 'ai_system_config', ['key'], unique=True)
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('user_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tag_id', name='uq_user_tag')
    )
    op.create_index(op.f('ix_user_tags_tag_id'), 'user_tags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_user_tags_user_id'), 'user_tags', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Seed initial tags and config
    op.execute("INSERT INTO tags (id, name, category, is_active) VALUES (gen_random_uuid(), 'Developer', 'Profession', true)")
    op.execute("INSERT INTO tags (id, name, category, is_active) VALUES (gen_random_uuid(), 'Designer', 'Profession', true)")
    op.execute("INSERT INTO tags (id, name, category, is_active) VALUES (gen_random_uuid(), 'Product Manager', 'Profession', true)")
    op.execute("INSERT INTO tags (id, name, category, is_active) VALUES (gen_random_uuid(), 'Founder', 'Profession', true)")
    op.execute("INSERT INTO tags (id, name, category, is_active) VALUES (gen_random_uuid(), 'Investor', 'Profession', true)")
    
    op.execute("INSERT INTO ai_system_config (id, key, value, description) VALUES (gen_random_uuid(), 'max_tags_per_user', '5', 'Maximum tags a user can select')")
    op.execute("INSERT INTO ai_system_config (id, key, value, description) VALUES (gen_random_uuid(), 'ai_memory_window_default', '\"unlimited\"', 'Default memory window')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tags_user_id'), table_name='user_tags')
    op.drop_index(op.f('ix_user_tags_tag_id'), table_name='user_tags')
    op.drop_table('user_tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_ai_system_config_key'), table_name='ai_system_config')
    op.drop_table('ai_system_config')
    # ### end Alembic commands ###
