"""add_indexes_and_constraints

Revision ID: 4e043bb0add2
Revises: 00b16a0c0c78
Create Date: 2026-08-19 01:42:27.659709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e043bb0add2'
down_revision: Union[str, Sequence[str], None] = '00b16a0c0c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_connection_request', 'connection_requests', ['sender_id', 'receiver_id'])
    op.alter_column('contact_memories', 'summary',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_contact_memories_contact_id'), table_name='contact_memories')
    op.create_index(op.f('ix_contact_memories_contact_id'), 'contact_memories', ['contact_id'], unique=True)
    op.alter_column('contacts', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_unique_constraint('uq_direct_conversation', 'direct_conversations', ['user_a_id', 'user_b_id'])
    op.create_check_constraint('chk_user_order', 'direct_conversations', 'user_a_id < user_b_id')
    op.create_index('ix_messages_conv_created_id', 'messages', ['conversation_id', 'created_at', 'id'], unique=False)
    op.create_unique_constraint('uq_client_message_id', 'messages', ['sender_user_id', 'client_message_id'])
    op.alter_column('recommendations', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recommendations', 'reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint('uq_client_message_id', 'messages', type_='unique')
    op.drop_index('ix_messages_conv_created_id', table_name='messages')
    op.drop_constraint('chk_user_order', 'direct_conversations', type_='check')
    op.drop_constraint('uq_direct_conversation', 'direct_conversations', type_='unique')
    op.alter_column('contacts', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_contact_memories_contact_id'), table_name='contact_memories')
    op.create_index(op.f('ix_contact_memories_contact_id'), 'contact_memories', ['contact_id'], unique=False)
    op.alter_column('contact_memories', 'summary',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('uq_connection_request', 'connection_requests', type_='unique')
    # ### end Alembic commands ###
