"""add last_message_content

Revision ID: 4e9a18f8ea91
Revises: 8f671eb1297d
Create Date: 2026-08-15 23:06:30.928692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9a18f8ea91'
down_revision: Union[str, Sequence[str], None] = '8f671eb1297d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_conversations', sa.Column('last_message_content', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direct_conversations', 'last_message_content')
    # ### end Alembic commands ###
