"""Add missing AI settings

Revision ID: a59018fc8fb7
Revises: 577ee827dc9b
Create Date: 2026-08-22 14:38:22.949572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59018fc8fb7'
down_revision: Union[str, Sequence[str], None] = '577ee827dc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('ai_read_profile', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('settings', sa.Column('ai_memory_refresh_interval', sa.String(length=50), server_default=sa.text("'realtime'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'ai_memory_refresh_interval')
    op.drop_column('settings', 'ai_read_profile')
    # ### end Alembic commands ###
